config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  root to: "static_pages#home"
   
  resources :odots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todo_lists do
    resources :todo_items, only: [:create]
  end

  resources :todo_items, only: [:destroy] do
    member do
      get "/done", to: "todo_items#done"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/odot.rb
class Odot < ApplicationRecord
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :content, presence: true
  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  validates :title, presence: true
  validates :archive, inclusion: { in: [ true, false ] }

  has_many :todo_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/odots_controller.rb
class OdotsController < ApplicationController
  before_action :set_odot, only: [:show, :edit, :update, :destroy]

  # GET /odots
  # GET /odots.json
  def index
    @odots = Odot.all
  end

  # GET /odots/1
  # GET /odots/1.json
  def show
  end

  # GET /odots/new
  def new
    @odot = Odot.new
  end

  # GET /odots/1/edit
  def edit
  end

  # POST /odots
  # POST /odots.json
  def create
    @odot = Odot.new(odot_params)

    respond_to do |format|
      if @odot.save
        format.html { redirect_to @odot, notice: 'Odot was successfully created.' }
        format.json { render :show, status: :created, location: @odot }
      else
        format.html { render :new }
        format.json { render json: @odot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /odots/1
  # PATCH/PUT /odots/1.json
  def update
    respond_to do |format|
      if @odot.update(odot_params)
        format.html { redirect_to @odot, notice: 'Odot was successfully updated.' }
        format.json { render :show, status: :ok, location: @odot }
      else
        format.html { render :edit }
        format.json { render json: @odot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /odots/1
  # DELETE /odots/1.json
  def destroy
    @odot.destroy
    respond_to do |format|
      format.html { redirect_to odots_url, notice: 'Odot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_odot
      @odot = Odot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def odot_params
      params.require(:odot).permit(:title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, except: [:create]

  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.build(todo_items_params)
    if @todo_item.save
      flash[:notice] = "Todo item created!"
      redirect_to @todo_list
    end
  end

  def destroy
    @todo_list = TodoList.find(@todo_item.todo_list_id)
    @todo_item.delete
    redirect_to @todo_list
  end

  def done
    @todo_list = TodoList.find(@todo_item.todo_list_id)
    @todo_item.update_attributes(done: true)
    redirect_to @todo_list
  end

  private

    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    def todo_items_params
      params.require(:todo_item).permit(:content)
    end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:edit, :update, :destroy, :show]

  def index
    @todo_lists = TodoList.all
  end

  def show
    @todo_item = TodoItem.new
    @todo_items = @todo_list.todo_items.all
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save
      flash[:notice] = "Todo List successfully created"
      redirect_to todo_lists_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @todo_list.update_attributes(todo_list_params)
      flash[:notice] = "Todo List successfully updated"
      redirect_to todo_lists_url
    else
      render 'edit'
    end
  end

  def destroy
    @todo_list.delete
    redirect_to todo_lists_url
  end

  private

    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/odots_helper.rb
module OdotsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/odots/_form.html.erb
<%= form_for(odot) do |f| %>
  <% if odot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(odot.errors.count, "error") %> prohibited this odot from being saved:</h2>

      <ul>
      <% odot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/odots/edit.html.erb
<h1>Editing Odot</h1>

<%= render 'form', odot: @odot %>

<%= link_to 'Show', @odot %> |
<%= link_to 'Back', odots_path %>

app/views/odots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Odots</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @odots.each do |odot| %>
      <tr>
        <td><%= odot.title %></td>
        <td><%= odot.description %></td>
        <td><%= link_to 'Show', odot %></td>
        <td><%= link_to 'Edit', edit_odot_path(odot) %></td>
        <td><%= link_to 'Destroy', odot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Odot', new_odot_path %>

app/views/odots/new.html.erb
<h1>New Odot</h1>

<%= render 'form', odot: @odot %>

<%= link_to 'Back', odots_path %>

app/views/odots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @odot.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @odot.description %>
</p>

<%= link_to 'Edit', edit_odot_path(@odot) %> |
<%= link_to 'Back', odots_path %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Todo List App</h1>
  <%= link_to "Create Todo List", new_todo_list_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "All Todo Lists", todo_lists_path, class: "btn btn-success btn-lg" %>
</div>

app/views/todo_lists/edit.html.erb
<h2>Edit Todo List</h2>

<%= form_for(@todo_list) do |f| %>

  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Todo List", class: "btn btn-default" %>
  </div>


<% end %>

app/views/todo_lists/index.html.erb
<h2>Your Todo Lists</h2>

<div class="row">
  <div class="col-xs-8">
    <p>
      You have created the below Todo Lists. Click on the title to see the todo list.
    </p>
  </div>
  <div class="col-xs-4">
    <%= link_to "Create New Todo List", new_todo_list_path, class: "btn btn-success" %>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= link_to todo_list.title, todo_list_path(todo_list) %></td>
        <td><%= todo_list.description %></td>
        <td>
          <%= link_to "Edit", edit_todo_list_path(todo_list), class: "btn btn-primary btn-sm", id: "edit_todo_list_#{todo_list.id}" %>
          <%= link_to "Delete", todo_list_path(todo_list), method: :delete, class: "btn btn-danger btn-sm", id: "delete_todo_list_#{todo_list.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todo_lists/new.html.erb
<h2>Create New Todo List</h2>

<%= form_for(@todo_list) do |f| %>

  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Todo List", class: "btn btn-default" %>
  </div>

<% end %>

app/views/todo_lists/show.html.erb
<h2><%= @todo_list.title %></h2>

<p><%= @todo_list.description %></p>

<div>
  Add your Todo list item here:
</div>

<%= form_for([@todo_list, @todo_item]) do |f| %>

  <div>
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :content, "Content", class: "hidden" %>
          <%= f.text_field :content, class: "form-control", placeholder: "Content" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= f.submit "Add Item", class: "btn btn-primary" %>
        </div>
      </div>
    </div>


  </div>

<% end %>

<!-- Todo Items -->

<ol class="list-group">
  <% @todo_items.each do |todo_item| %>
    <li class='list-group-item clearfix <%= "list-group-item-info" if todo_item.done %>'>
      <h5 class="pull-right"><%= todo_item.done ? "Done" : "Pending" %></h5>
      <h4><%= todo_item.content %></h4>
      <%= link_to "Mark as done", done_todo_item_path(todo_item), class: "btn btn-success btn-sm", id: "mark_as_done_#{todo_item.id}" if !todo_item.done %>
      <%= link_to "Delete Item", todo_item_path(todo_item), method: :delete, class: "btn btn-danger btn-sm", id: "delete_todo_item_#{todo_item.id}" %>
    </li>
  <% end %>
</ol>

<%= link_to "Back to Todo Lists", todo_lists_path, class: "btn btn-primary" %>